// NOTE: This file is intended to be GENERATED by `openapi-typescript`.
// For now we keep a minimal hand-written stub that matches the FastAPI
// demo models in backend/backend/main.py so the typed client compiles.
//
// Once you run the backend (uvicorn backend.backend.main:app) and execute
// `npm run openapi:gen`, this file will be overwritten with a full
// schema derived from the FastAPI OpenAPI spec.

export interface FooRequest {
  foo: string;
}

export interface FooResponse {
  bar: string;
}

// Minimal `paths` type compatible with `openapi-typescript`/`openapi-fetch`.
// We only model the parts we actually use in the app.
export interface paths {
  "/foo": {
    post: {
      requestBody: {
        content: {
          "application/json": FooRequest;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": FooResponse[];
          };
        };
      };
    };
  };
}
